joint_limits:
  j1:
    has_position_limits: true
    min_position: -2.879
    max_position: 2.879
    has_velocity_limits: true
    max_velocity: 2.
    has_acceleration_limits: true
    max_acceleration: 5
  j2:
    has_position_limits: true
    min_position: -1.605
    max_position: 2.268
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 5
  j3:
    has_position_limits: true
    min_position: -2.164
    max_position: 2.809
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: true
    max_acceleration: 5
  j4:
    has_position_limits: true
    min_position: -2.705
    max_position: 2.705
    has_velocity_limits: true
    max_velocity: 3.5
    has_acceleration_limits: true
    max_acceleration: 5
  j5:
    has_position_limits: true
    min_position: -1.66
    max_position: 1.66
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: true
    max_acceleration: 15
  j6:
    has_position_limits: true
    min_position: -3.4
    max_position: 3.4
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: true
    max_acceleration: 15
  schunk_pg70_finger_left_joint:
    has_position_limits: true
    min_position: 0.0005
    max_position: 0.0320
    has_velocity_limits: true
    max_velocity: 0.0018
    has_acceleration_limits: false
    max_acceleration: 0
  schunk_pg70_finger_right_joint:
    has_position_limits: true
    min_position: 0.0005
    max_position: 0.0320
    has_velocity_limits: true
    max_velocity: 0.0018
    has_acceleration_limits: false
    max_acceleration: 0

