joint_limits:
  j1:
    has_position_limits: true
    min_position: -2.879
    max_position: 2.879
    has_velocity_limits: true
    max_velocity: 1.75
    has_acceleration_limits: true
    max_acceleration: 14
  j2:
    has_position_limits: true
    min_position: -1.605
    max_position: 2.268
    has_velocity_limits: true
    max_velocity: 1.4
    has_acceleration_limits: false
    max_acceleration: 11.2
  j3:
    has_position_limits: true
    min_position: -1.78
    max_position: 2.809
    has_velocity_limits: true
    max_velocity: 1.75
    has_acceleration_limits: false
    max_acceleration: 14
  j4:
    has_position_limits: true
    min_position: -2.705
    max_position: 2.705
    has_velocity_limits: true
    max_velocity: 1.535
    has_acceleration_limits: false
    max_acceleration: 12.28
  j5:
    has_position_limits: true
    min_position: -2
    max_position: 2
    has_velocity_limits: true
    max_velocity: 1.9625
    has_acceleration_limits: false
    max_acceleration: 15.7
  j6:
    has_position_limits: true
    min_position: -6.1
    max_position: 6.1
    has_velocity_limits: true
    max_velocity: 2.88
    has_acceleration_limits: false
    max_acceleration: 23
