joint_limits:
  j1:
    has_position_limits: true
    min_position: -2.879
    max_position: 2.879
    has_velocity_limits: true
    max_velocity: 2.
    has_acceleration_limits: true
    max_acceleration: 5
  j2:
    has_position_limits: true
    min_position: -1.605
    max_position: 2.268
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 5
  j3:
    has_position_limits: true
    min_position: -2.164
    max_position: 2.809
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: true
    max_acceleration: 5
  j4:
    has_position_limits: true
    min_position: -2.705
    max_position: 2.705
    has_velocity_limits: true
    max_velocity: 3.5
    has_acceleration_limits: true
    max_acceleration: 5
  j5:
    has_position_limits: true
    min_position: -1.8325
    max_position: 1.8325
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: true
    max_acceleration: 15
  j6:
    has_position_limits: true
    min_position: -6.1959
    max_position: 6.1959
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: true
    max_acceleration: 15
