arm:
  kinematics_solver: srv_kinematics_plugin/SrvKinematicsPlugin  # defines the use of srv_kinematics_plugin

  # All angles are in DEGREES!!
  # All translations are in METERS!!

  # defines transformation from the last system (of the used model) to end effector system
  base_robot_frame: "base_link"
  last_robot_frame: "last_robot_frame"
  # eef_robot_frame: "planning_tip"

  # defines lengths of links accoardingly to schematics, lenghts are in meters
  link_lengths:
    - 0.35
    - 0.085
    - 0.38
    - 0.1
    - 0.425
    - 0.085

  # defines joints' zero positions offsets from used model
  joint_offsets:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0

  # defines the direction of the joints.
  # if positive direcition is same as in the used model, use '+'
  # else use '-'
  joint_directions:
    - '+'
    - '+'
    - '+'
    - '+'
    - '+'
    - '+'

  # defines configuration by 3 bit string
  #         for closest solution to return use
  #         "xxx"
  configuration: "xxx"

  # defines whether mark joints with infinity solutions
  # infinity_solutions: False

  # defines names under which are loaded joint limits to parameter server
  joint_limits_names:
    - 'j1'
    - 'j2'
    - 'j3'
    - 'j4'
    - 'j5'
    - 'j6'
