(cl:defpackage kinematics_6dof_ros_pkg-srv
  (:use )
  (:export
   "CHANGEKINEMATICSCONFIG"
   "<CHANGEKINEMATICSCONFIG-REQUEST>"
   "CHANGEKINEMATICSCONFIG-REQUEST"
   "<CHANGEKINEMATICSCONFIG-RESPONSE>"
   "CHANGEKINEMATICSCONFIG-RESPONSE"
  ))

